# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Use Node.js latest
      #uses: actions/setup-node@v3
      #with:
        #node-version: latest
        #cache: 'npm'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    # Log in to Docker registry
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # Build Docker image
    - name: Build Docker image
      run: docker build -t atulaman/test2:latest .
        
      # Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push atulaman/test2:latest
      # Run Docker container
    - name: Run Docker container
      run: docker run -d -p 3000:3000 atulaman/test2:latest
